name: Mern Authenticaiton API

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Use Node

      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install Dependencies
      - run: npm install

      - name: Build Project
      - run: npm build
    
